services:
  spring-rest-service-2:
    #image: docker.io/library/spring-petclinic:3.5.0-SNAPSHOT
    #image: springcommunity/spring-petclinic-rest:3.4.3
    image: spring-rest-service:feature
    container_name: spring-rest-energy-test-2
    cgroup_parent: energy-consumption-experiment-2.slice
    #deploy:
    #  replicas: 10
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.jpa.show-sql": "false",
          "spring.jpa.properties.hibernate.show_sql": "false",
          "server.tomcat.threads.max": 100
        }'
    expose:
      - "8111"
    ports:
      - "8111:8081"
